# Generated by Django 2.1.5 on 2019-02-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_auto_20190213_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.CharField(max_length=10),
        ),
    ]
